import type { Recipe } from '@/types/recipe';
import { TAGS } from '@/config/constants';

/**
 * 预置菜谱种子数据
 * 涵盖荤菜、素菜、汤、早餐、主食、简餐等多个分类，约 120 道家常菜
 */
export const SEED_RECIPES: Omit<Recipe, 'id'>[] = [
  // ============== 早餐干食 (bf_dry) - 12 道 ==============
  {
    name: '猪肉大葱包子',
    category: 'bf_dry',
    tags: [],
    ingredients: ['面粉', '酵母', '猪肉馅', '大葱', '生抽', '香油', '姜末'],
    instructions: '1. 面粉加酵母温水和面发酵至两倍大；2. 猪肉馅加葱姜、生抽、香油拌匀；3. 擀皮包入馅料捏褶；4. 二次醒发 15 分钟；5. 冷水上锅蒸 15 分钟焖 3 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '白面馒头',
    category: 'bf_dry',
    tags: [],
    ingredients: ['面粉', '酵母', '温水', '白糖'],
    instructions: '1. 面粉加酵母、糖、温水和成光滑面团；2. 发酵至两倍大；3. 排气分剂揉成馒头胚；4. 二次醒发 20 分钟；5. 冷水上锅蒸 15 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '葱油花卷',
    category: 'bf_dry',
    tags: [],
    ingredients: ['面粉', '酵母', '小葱', '食用油', '盐'],
    instructions: '1. 发面至两倍大；2. 擀大片刷油撒盐和葱花；3. 卷起切段拧成花卷；4. 醒发 15 分钟；5. 冷水上锅蒸 15 分钟。',
    rating: null,
    history_dates: [],
  },

  {
    name: '油条',
    category: 'bf_dry',
    tags: [],
    ingredients: ['高筋面粉', '泡打粉', '小苏打', '盐', '鸡蛋', '食用油'],
    instructions: '1. 面粉加泡打粉、苏打、盐、蛋和水揉光滑；2. 冷藏松弛 4 小时以上；3. 擀长条切小段；4. 两段叠加压扁拉长；5. 油温六成热下锅炸至金黄。',
    rating: null,
    history_dates: [],
  },
  {
    name: '芝麻烧饼',
    category: 'bf_dry',
    tags: [],
    ingredients: ['面粉', '酵母', '芝麻', '食用油', '盐', '五香粉'],
    instructions: '1. 发面 1 小时；2. 擀片刷油撒盐五香粉卷起；3. 切剂擀圆刷糖水粘芝麻；4. 烤箱 200 度烤 15 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '肉粽',
    category: 'bf_dry',
    tags: [],
    ingredients: ['糯米', '五花肉', '粽叶', '生抽', '老抽', '料酒', '五香粉'],
    instructions: '1. 糯米浸泡 4 小时；2. 五花肉用生抽老抽料酒腌制 2 小时；3. 粽叶折斗装米和肉；4. 包紧捆绳；5. 冷水下锅煮 2 小时。',
    rating: null,
    history_dates: [],
  },
  {
    name: '水煮玉米',
    category: 'bf_dry',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['甜玉米', '清水', '盐'],
    instructions: '1. 玉米剥外皮留嫩衣；2. 冷水下锅加少许盐；3. 大火烧开转中火煮 15 分钟；4. 捞出晾凉。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒸红薯',
    category: 'bf_dry',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['红薯'],
    instructions: '1. 红薯洗净不去皮；2. 切大块或整根放蒸屉；3. 水开后蒸 25 分钟；4. 筷子能轻松扎透即可。',
    rating: null,
    history_dates: [],
  },
  {
    name: '烤面包片',
    category: 'bf_dry',
    tags: [],
    ingredients: ['吐司面包', '黄油', '果酱'],
    instructions: '1. 吐司放烤面包机或平底锅；2. 烤至两面金黄；3. 趁热抹黄油或果酱。',
    rating: null,
    history_dates: [],
  },
  {
    name: '葱油饼',
    category: 'bf_dry',
    tags: [],
    ingredients: ['面粉', '小葱', '食用油', '盐', '温水'],
    instructions: '1. 温水和面醒 30 分钟；2. 擀薄片刷油撒盐和葱花；3. 卷起盘成圆饼；4. 平底锅小火两面煎至金黄。',
    rating: null,
    history_dates: [],
  },
  {
    name: '鸡蛋灌饼',
    category: 'bf_dry',
    tags: [],
    ingredients: ['面粉', '鸡蛋', '生菜', '甜面酱', '葱花', '食用油'],
    instructions: '1. 烫面醒 30 分钟擀成饼坯；2. 平底锅煎至鼓起划口；3. 灌入打散的蛋液继续煎；4. 抹甜面酱卷生菜。',
    rating: null,
    history_dates: [],
  },
  {
    name: '手抓饼',
    category: 'bf_dry',
    tags: [],
    ingredients: ['手抓饼面胚', '鸡蛋', '生菜', '火腿', '沙拉酱'],
    instructions: '1. 平底锅小火放入饼胚；2. 一面金黄翻面；3. 打入鸡蛋摊开；4. 加生菜火腿挤沙拉酱卷起。',
    rating: null,
    history_dates: [],
  },

  // ============== 早餐蛋类 (bf_egg) - 6 道 ==============
  {
    name: '白煮鸡蛋',
    category: 'bf_egg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鸡蛋', '清水'],
    instructions: '1. 鸡蛋洗净放冷水锅；2. 大火煮开转中火 6-8 分钟；3. 捞出过冷水即可剥壳。',
    rating: null,
    history_dates: [],
  },
  {
    name: '荷包蛋',
    category: 'bf_egg',
    tags: [],
    ingredients: ['鸡蛋', '食用油', '盐'],
    instructions: '1. 平底锅加少许油加热；2. 打入鸡蛋小火慢煎；3. 蛋白凝固后翻面；4. 撒少许盐出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒸水蛋',
    category: 'bf_egg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鸡蛋', '温水', '盐', '生抽', '香油'],
    instructions: '1. 鸡蛋打散加 1.5 倍温水和盐拌匀；2. 过筛去泡沫；3. 盖保鲜膜蒸 10 分钟；4. 出锅淋生抽香油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '煎鸡蛋',
    category: 'bf_egg',
    tags: [],
    ingredients: ['鸡蛋', '食用油', '盐'],
    instructions: '平底锅热油，打入鸡蛋，小火煎至底部金黄，撒少许盐即可',
    rating: null,
    history_dates: [],
  },
  {
    name: '玉子烧',
    category: 'bf_egg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鸡蛋', '牛奶', '盐', '糖'],
    instructions: '鸡蛋加牛奶、盐、糖打散，玉子烧锅分次倒入蛋液，卷起成型',
    rating: null,
    history_dates: [],
  },
  {
    name: '炒鸡蛋',
    category: 'bf_egg',
    tags: [],
    ingredients: ['鸡蛋', '葱花', '盐', '食用油'],
    instructions: '鸡蛋打散加盐，热油下蛋液快速翻炒至凝固，撒葱花',
    rating: null,
    history_dates: [],
  },

  // ============== 早餐稀食-成人/老人 (bf_wet_adult) - 8 道 ==============
  {
    name: '牛奶燕麦片',
    category: 'bf_wet_adult',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['即食燕麦片', '纯牛奶', '蜂蜜'],
    instructions: '1. 燕麦片倒入碗中；2. 加热牛奶冲泡；3. 静置 2 分钟；4. 可加蜂蜜调味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '小米粥',
    category: 'bf_wet_adult',
    tags: [TAGS.ELDERLY_FRIENDLY, TAGS.PORRIDGE],
    ingredients: ['小米', '清水'],
    instructions: '1. 小米淘洗干净；2. 冷水下锅大火烧开；3. 转小火慢熬 30 分钟；4. 期间搅拌防糊底。',
    rating: null,
    history_dates: [],
  },
  {
    name: '南瓜粥',
    category: 'bf_wet_adult',
    tags: [TAGS.ELDERLY_FRIENDLY, TAGS.PORRIDGE],
    ingredients: ['大米', '南瓜', '清水', '冰糖'],
    instructions: '1. 南瓜去皮切块；2. 大米和南瓜冷水下锅；3. 大火煮开转小火 40 分钟；4. 加冰糖搅匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '现磨豆浆',
    category: 'bf_wet_adult',
    tags: [],
    ingredients: ['黄豆', '清水', '白糖'],
    instructions: '1. 黄豆提前浸泡 8 小时；2. 倒入豆浆机加水至刻度；3. 启动豆浆程序约 25 分钟；4. 过滤豆渣加糖。',
    rating: null,
    history_dates: [],
  },
  {
    name: '红豆薏米水',
    category: 'bf_wet_adult',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['红豆', '薏米', '清水', '冰糖'],
    instructions: '1. 红豆薏米浸泡 4 小时；2. 加足量水大火煮开；3. 转小火炖 1 小时至豆开花；4. 加冰糖搅匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '黑芝麻糊',
    category: 'bf_wet_adult',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['黑芝麻', '糯米粉', '白糖', '清水'],
    instructions: '1. 黑芝麻炒香研磨成粉；2. 糯米粉加水调浆；3. 与芝麻粉一同倒入锅中小火搅煮；4. 加糖煮至浓稠。',
    rating: null,
    history_dates: [],
  },
  {
    name: '紫薯银耳羹',
    category: 'bf_wet_adult',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['银耳', '紫薯', '冰糖', '红枣', '清水'],
    instructions: '1. 银耳泡发撕小朵；2. 紫薯去皮切丁；3. 全部入锅加水；4. 大火烧开转小火炖 1 小时至出胶；5. 加冰糖。',
    rating: null,
    history_dates: [],
  },
  {
    name: '玉米糊',
    category: 'bf_wet_adult',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['玉米面', '清水', '白糖'],
    instructions: '1. 玉米面用冷水调散；2. 锅中烧开水缓慢倒入玉米浆；3. 不停搅拌防结块；4. 小火煮 10 分钟加糖。',
    rating: null,
    history_dates: [],
  },

  // ============== 早餐稀食-儿童 (bf_wet_kid) - 2 道 ==============
  {
    name: '纯牛奶',
    category: 'bf_wet_kid',
    tags: [],
    ingredients: ['纯牛奶'],
    instructions: '1. 牛奶倒入杯中；2. 微波炉加热 1 分钟或隔水温热；3. 温度适宜后饮用。',
    rating: null,
    history_dates: [],
  },
  {
    name: '豆浆',
    category: 'bf_wet_kid',
    tags: [],
    ingredients: ['黄豆', '清水', '白糖'],
    instructions: '1. 黄豆泡发；2. 豆浆机加水启动程序；3. 过滤豆渣；4. 加适量白糖搅匀。',
    rating: null,
    history_dates: [],
  },

  // ============== 荤菜 (meat) - 42 道 ==============
  {
    name: '红烧肉',
    category: 'meat',
    tags: [],
    ingredients: ['五花肉', '生抽', '老抽', '冰糖', '八角', '桂皮', '料酒', '葱姜'],
    instructions: '1. 五花肉切块焯水；2. 锅中冰糖小火炒糖色；3. 下肉块翻炒上色；4. 加生抽老抽料酒香料和热水；5. 大火烧开转小火炖 60 分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '清蒸鲈鱼',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鲈鱼', '葱', '姜', '蒸鱼豉油', '料酒', '食用油'],
    instructions: '1. 鲈鱼去鳞内脏洗净两面划刀；2. 抹料酒铺姜片；3. 水开上锅蒸 8 分钟；4. 倒掉汤汁铺葱丝淋豉油；5. 浇热油激香。',
    rating: null,
    history_dates: [],
  },
  {
    name: '可乐鸡翅',
    category: 'meat',
    tags: [],
    ingredients: ['鸡翅中', '可乐', '生抽', '老抽', '料酒', '姜片', '葱段'],
    instructions: '1. 鸡翅两面划刀焯水；2. 锅中少油煎至两面金黄；3. 加葱姜生抽老抽料酒；4. 倒入可乐没过鸡翅；5. 大火烧开转中小火炖 20 分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '糖醋排骨',
    category: 'meat',
    tags: [],
    ingredients: ['猪小排', '醋', '白糖', '生抽', '料酒', '番茄酱', '姜片'],
    instructions: '1. 排骨焯水；2. 按一勺料酒、二勺生抽、三勺糖、四勺醋、五勺水比例调汁；3. 油煎排骨上色；4. 倒汁加姜片烧开；5. 中小火炖 30 分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '红烧牛腩',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY, TAGS.WINTER_RECOMMENDED],
    ingredients: ['牛腩', '萝卜', '生抽', '老抽', '冰糖', '八角', '桂皮', '香叶', '姜片'],
    instructions: '1. 牛腩切块冷水焯出血沫；2. 炒糖色下牛肉翻炒；3. 加调料和热水；4. 高压锅压 30 分钟或炖 90 分钟；5. 加萝卜再炖 20 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '宫保鸡丁',
    category: 'meat',
    tags: [TAGS.SPICY],
    ingredients: ['鸡腿肉', '花生米', '干辣椒', '花椒', '葱白', '生抽', '醋', '糖', '淀粉'],
    instructions: '1. 鸡丁加生抽淀粉腌制；2. 调糖醋汁；3. 热油爆香花椒辣椒；4. 下鸡丁炒至变色；5. 加葱白花生倒汁勾芡。',
    rating: null,
    history_dates: [],
  },
  {
    name: '鱼香肉丝',
    category: 'meat',
    tags: [],
    ingredients: ['猪里脊', '木耳', '胡萝卜', '青椒', '泡椒', '蒜末', '糖', '醋', '生抽'],
    instructions: '1. 肉丝上浆腌制；2. 调鱼香汁(糖醋生抽淀粉)；3. 热油滑炒肉丝盛出；4. 爆香蒜泡椒下配菜；5. 回锅加汁翻炒收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '回锅肉',
    category: 'meat',
    tags: [],
    ingredients: ['五花肉', '青蒜苗', '青椒', '豆瓣酱', '甜面酱', '生抽', '料酒'],
    instructions: '1. 五花肉冷水煮至断生切薄片；2. 锅中煸炒出油；3. 加豆瓣酱甜面酱炒香；4. 下青椒蒜苗；5. 调生抽翻炒断生。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜蓉开背虾',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['基围虾', '蒜末', '粉丝', '生抽', '蒸鱼豉油', '小米椒', '葱花'],
    instructions: '1. 虾开背去虾线；2. 粉丝泡软铺盘；3. 蒜末炒香铺虾上；4. 水开蒸 6 分钟；5. 淋豉油热油激香撒葱。',
    rating: null,
    history_dates: [],
  },
  {
    name: '清蒸多宝鱼',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['多宝鱼', '葱', '姜', '蒸鱼豉油', '料酒'],
    instructions: '1. 鱼洗净两面抹料酒；2. 盘底垫葱姜；3. 大火上汽蒸 8 分钟；4. 倒汤铺葱丝；5. 浇豉油和热油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '红烧鸡腿',
    category: 'meat',
    tags: [],
    ingredients: ['琵琶腿', '生抽', '老抽', '冰糖', '料酒', '八角', '葱姜'],
    instructions: '1. 鸡腿划刀焯水；2. 炒糖色下鸡腿；3. 加生抽老抽料酒和热水；4. 加香料葱姜小火炖 25 分钟；5. 大火收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '肉末豆腐',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['嫩豆腐', '猪肉末', '生抽', '蚝油', '葱花', '蒜末', '淀粉水'],
    instructions: '1. 豆腐切块焯水；2. 肉末炒散加蒜末；3. 加生抽蚝油和清水；4. 下豆腐烧 5 分钟；5. 勾薄芡撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒸肉饼',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['猪肉馅', '马蹄', '鸡蛋', '生抽', '料酒', '盐', '淀粉', '葱花'],
    instructions: '1. 马蹄剁碎与肉馅混合；2. 加蛋、生抽、料酒、盐、淀粉顺一方向搅打；3. 摊平入盘；4. 水开蒸 20 分钟；5. 撒葱花淋热油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '番茄牛腩',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['牛腩', '番茄', '番茄酱', '洋葱', '生抽', '冰糖', '姜片'],
    instructions: '1. 牛腩切块焯水；2. 洋葱番茄炒出沙；3. 加番茄酱炒香；4. 倒入牛腩和热水；5. 高压锅压 30 分钟或慢炖 90 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '香菇滑鸡',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鸡腿肉', '香菇', '生抽', '蚝油', '料酒', '淀粉', '姜丝'],
    instructions: '1. 鸡肉切块加生抽蚝油料酒淀粉腌 20 分钟；2. 香菇泡发切片；3. 摆盘加姜丝；4. 大火蒸 15 分钟；5. 撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '酱爆鸡丁',
    category: 'meat',
    tags: [],
    ingredients: ['鸡胸肉', '黄瓜', '甜面酱', '生抽', '糖', '葱姜', '淀粉'],
    instructions: '1. 鸡丁上浆腌制；2. 黄瓜切丁；3. 热油滑鸡丁盛出；4. 爆香葱姜下甜面酱炒香；5. 回锅加黄瓜调味翻炒。',
    rating: null,
    history_dates: [],
  },
  {
    name: '水煮肉片',
    category: 'meat',
    tags: [TAGS.SPICY],
    ingredients: ['里脊肉片', '豆芽', '生菜', '豆瓣酱', '干辣椒', '花椒', '蒜末', '淀粉'],
    instructions: '1. 肉片上浆；2. 豆芽生菜焯水垫底；3. 豆瓣酱炒红油；4. 加水烧开下肉片煮熟连汤倒入；5. 撒蒜末辣椒花椒淋热油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '红烧排骨',
    category: 'meat',
    tags: [],
    ingredients: ['猪肋排', '生抽', '老抽', '冰糖', '料酒', '八角', '葱姜'],
    instructions: '1. 排骨焯水洗净；2. 炒糖色下排骨翻炒上色；3. 加调料和热水；4. 小火炖 40 分钟；5. 大火收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '青椒肉丝',
    category: 'meat',
    tags: [],
    ingredients: ['猪里脊', '青椒', '生抽', '料酒', '淀粉', '蒜末'],
    instructions: '1. 肉丝加生抽料酒淀粉腌制；2. 青椒切丝；3. 热油滑炒肉丝至变色盛出；4. 爆香蒜末下青椒；5. 回锅调味翻炒断生。',
    rating: null,
    history_dates: [],
  },
  {
    name: '黄焖鸡',
    category: 'meat',
    tags: [],
    ingredients: ['鸡腿肉', '青椒', '土豆', '酱油', '料酒', '姜片', '蒜瓣'],
    instructions: '1. 鸡腿肉切块焯水；2. 热油爆香姜蒜下鸡块煸炒；3. 加酱油料酒翻炒上色；4. 加土豆和热水炖 20 分钟；5. 加青椒再焖 5 分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '土豆烧牛肉',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['牛腩', '土豆', '胡萝卜', '洋葱', '生抽', '老抽', '姜片', '八角'],
    instructions: '1. 牛腩切块冷水焯出血沫；2. 锅中爆香洋葱姜片；3. 下牛肉加生抽老抽八角翻炒；4. 加热水高压锅压 25 分钟；5. 加土豆胡萝卜再炖 15 分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蚝油牛肉',
    category: 'meat',
    tags: [],
    ingredients: ['牛里脊', '西兰花', '蚝油', '生抽', '料酒', '淀粉', '蒜末'],
    instructions: '1. 牛肉切薄片加生抽料酒淀粉腌 15 分钟；2. 西兰花焯水备用；3. 热油滑炒牛肉至变色盛出；4. 爆香蒜末下西兰花；5. 回锅加蚝油翻炒勾薄芡。',
    rating: null,
    history_dates: [],
  },
  {
    name: '酸菜鱼',
    category: 'meat',
    tags: [TAGS.SPICY],
    ingredients: ['草鱼片', '酸菜', '泡椒', '蒜末', '姜末', '料酒', '蛋清', '淀粉'],
    instructions: '1. 鱼片加蛋清淀粉料酒腌制；2. 酸菜切段挤干；3. 热油爆香姜蒜泡椒下酸菜炒香；4. 加水烧开煮 5 分钟；5. 下鱼片煮 2 分钟连汤倒入碗中。',
    rating: null,
    history_dates: [],
  },
  {
    name: '京酱肉丝',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['猪里脊', '甜面酱', '大葱', '豆腐皮', '生抽', '料酒', '糖', '淀粉'],
    instructions: '1. 肉丝加生抽料酒淀粉腌制；2. 大葱切丝豆腐皮切方片；3. 热油滑炒肉丝盛出；4. 调甜面酱加糖小火炒香；5. 回锅肉丝裹酱出锅，配葱丝豆腐皮卷食。',
    rating: null,
    history_dates: [],
  },
  {
    name: '葱爆羊肉',
    category: 'meat',
    tags: [],
    ingredients: ['羊肉片', '大葱', '生抽', '料酒', '蒜末', '花椒', '孜然粉'],
    instructions: '1. 羊肉片加料酒生抽腌制；2. 大葱斜切段；3. 热油爆花椒蒜末下羊肉大火快炒；4. 肉变色加葱段；5. 撒孜然粉翻匀出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '椒盐排骨',
    category: 'meat',
    tags: [],
    ingredients: ['猪小排', '花椒盐', '料酒', '生抽', '姜片', '淀粉', '面粉'],
    instructions: '1. 排骨加料酒生抽姜片腌 30 分钟；2. 拍上淀粉面粉；3. 油温六成炸至金黄捞出；4. 油温升高复炸 30 秒；5. 撒花椒盐翻匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '糖醋鱼',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['黄花鱼', '番茄酱', '白糖', '白醋', '生抽', '淀粉', '姜葱'],
    instructions: '1. 鱼两面划刀拍淀粉；2. 油锅煎至两面金黄盛出；3. 调番茄酱糖醋生抽汁；4. 锅中倒汁烧开勾薄芡；5. 浇在鱼上撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '白切鸡',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['三黄鸡', '姜片', '葱段', '料酒', '盐', '沙姜末', '蒜末', '生抽'],
    instructions: '1. 鸡腹腔塞姜葱抹料酒；2. 水开提鸡三上三下浸入；3. 小火浸煮 25 分钟关火焖 10 分钟；4. 捞出过冰水让皮脆；5. 斩件配沙姜蒜蓉生抽蘸料。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蚂蚁上树',
    category: 'meat',
    tags: [],
    ingredients: ['粉丝', '猪肉末', '豆瓣酱', '生抽', '料酒', '蒜末', '葱花'],
    instructions: '1. 粉丝温水泡软；2. 热油下肉末炒散加料酒；3. 加豆瓣酱蒜末炒香红油；4. 加水生抽烧开下粉丝；5. 收汁撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '木须肉',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['猪里脊', '鸡蛋', '木耳', '黄瓜', '胡萝卜', '葱姜', '生抽'],
    instructions: '1. 肉片上浆腌制；2. 木耳泡发胡萝卜黄瓜切片；3. 热油炒蛋盛出；4. 滑炒肉片盛出；5. 爆香葱姜下配菜回锅鸡蛋肉片调味翻炒。',
    rating: null,
    history_dates: [],
  },
  {
    name: '锅包肉',
    category: 'meat',
    tags: [],
    ingredients: ['猪里脊', '番茄酱', '白糖', '白醋', '胡萝卜丝', '葱姜', '淀粉'],
    instructions: '1. 肉切大片裹厚淀粉糊；2. 油温六成炸至定型捞出；3. 油温升高复炸至酥脆；4. 锅留底油下番茄酱糖醋汁烧开；5. 倒入肉片快速翻匀撒葱姜丝。',
    rating: null,
    history_dates: [],
  },
  {
    name: '辣子鸡',
    category: 'meat',
    tags: [TAGS.SPICY],
    ingredients: ['鸡腿肉', '干辣椒', '花椒', '蒜末', '姜末', '料酒', '生抽', '淀粉'],
    instructions: '1. 鸡丁加生抽料酒淀粉腌制；2. 油温六成炸至外酥；3. 锅留底油爆香姜蒜花椒干辣椒；4. 倒入鸡丁大火翻炒；5. 调味出锅撒白芝麻。',
    rating: null,
    history_dates: [],
  },
  {
    name: '豆角焖肉',
    category: 'meat',
    tags: [],
    ingredients: ['五花肉', '豇豆', '土豆', '生抽', '老抽', '八角', '姜片'],
    instructions: '1. 五花肉切块煸出油；2. 加姜片八角生抽老抽炒香；3. 加豇豆土豆翻炒；4. 加热水没过食材；5. 中小火焖 30 分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '咖喱鸡肉',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鸡腿肉', '土豆', '胡萝卜', '洋葱', '咖喱块', '椰浆'],
    instructions: '1. 鸡肉切块；2. 热油炒香洋葱下鸡肉煎至变色；3. 加土豆胡萝卜翻炒；4. 加水没过食材炖 15 分钟；5. 放咖喱块和椰浆煮至浓稠。',
    rating: null,
    history_dates: [],
  },
  {
    name: '西芹炒牛肉',
    category: 'meat',
    tags: [],
    ingredients: ['牛里脊', '西芹', '蚝油', '生抽', '料酒', '淀粉', '蒜末'],
    instructions: '1. 牛肉切片加生抽料酒淀粉腌制；2. 西芹斜切段焯水；3. 热油滑炒牛肉盛出；4. 爆香蒜末下西芹；5. 回锅加蚝油翻炒。',
    rating: null,
    history_dates: [],
  },
  {
    name: '粉蒸肉',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['五花肉', '蒸肉粉', '南瓜', '腐乳', '生抽', '姜末', '葱花'],
    instructions: '1. 五花肉切薄片加腐乳生抽姜末腌 30 分钟；2. 裹匀蒸肉粉；3. 南瓜切块铺碗底；4. 肉片码在南瓜上；5. 大火蒸 60 分钟撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '啤酒鸭',
    category: 'meat',
    tags: [],
    ingredients: ['鸭腿', '啤酒', '生抽', '老抽', '冰糖', '姜片', '八角', '葱段'],
    instructions: '1. 鸭肉切块焯水；2. 锅中爆香姜葱八角下鸭块煸出油；3. 加生抽老抽冰糖翻炒上色；4. 倒入啤酒没过鸭肉；5. 大火烧开转小火炖 40 分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '红烧狮子头',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['猪肉馅', '马蹄', '鸡蛋', '生抽', '老抽', '料酒', '葱姜', '淀粉'],
    instructions: '1. 马蹄剁碎与肉馅蛋液葱姜调料搅打上劲；2. 团成大肉丸；3. 油温六成炸至定型；4. 锅中加生抽老抽料酒和热水；5. 下肉丸小火炖 40 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '香辣虾',
    category: 'meat',
    tags: [TAGS.SPICY],
    ingredients: ['鲜虾', '干辣椒', '花椒', '蒜末', '姜片', '豆瓣酱', '料酒'],
    instructions: '1. 虾开背去虾线；2. 热油煎虾两面变红盛出；3. 锅中爆香姜蒜花椒干辣椒；4. 加豆瓣酱炒红油；5. 回锅虾加料酒翻炒收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '板栗烧鸡',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鸡腿肉', '板栗', '生抽', '老抽', '冰糖', '料酒', '姜葱'],
    instructions: '1. 鸡块焯水；2. 板栗去壳；3. 锅中炒糖色下鸡块上色；4. 加生抽老抽料酒姜葱和热水；5. 加板栗炖 30 分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜香排骨',
    category: 'meat',
    tags: [],
    ingredients: ['猪小排', '大蒜', '生抽', '蚝油', '料酒', '糖', '淀粉'],
    instructions: '1. 排骨加生抽蚝油料酒糖蒜末腌 1 小时；2. 拍少许淀粉；3. 烤箱 180 度烤 25 分钟；4. 翻面再烤 10 分钟；5. 撒蒜末出炉。',
    rating: null,
    history_dates: [],
  },
  {
    name: '椒麻鸡',
    category: 'meat',
    tags: [TAGS.SPICY, TAGS.COLD_DISH],
    ingredients: ['鸡腿肉', '花椒', '小米椒', '蒜末', '姜末', '生抽', '香醋', '香油', '葱花'],
    instructions: '1. 鸡腿煮 15 分钟过冰水；2. 撕成条状摆盘；3. 花椒小米椒葱花剁碎；4. 加蒜姜生抽醋香油拌成椒麻汁；5. 浇在鸡肉上拌匀。',
    rating: null,
    history_dates: [],
  },

  // ============== 新增荤菜 (meat) - 29 道 ==============
  {
    name: '口水鸡',
    category: 'meat',
    tags: [TAGS.COLD_DISH, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['鸡腿肉', '花椒', '辣椒油', '蒜末', '生抽', '香醋', '花生碎', '葱花'],
    instructions: '1. 鸡腿煮熟过冰水切块摆盘；2. 花椒油加蒜末辣椒油生抽醋调汁；3. 浇汁撒花生碎葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '照烧鸡腿',
    category: 'meat',
    tags: [],
    ingredients: ['鸡腿', '生抽', '味淋', '蜂蜜', '姜片', '食用油'],
    instructions: '1. 鸡腿去骨划刀腌制30分钟；2. 平底锅煎至两面金黄；3. 加照烧汁小火收至浓稠。',
    rating: null,
    history_dates: [],
  },
  {
    name: '三杯鸡',
    category: 'meat',
    tags: [],
    ingredients: ['鸡腿肉', '九层塔', '姜片', '蒜瓣', '酱油', '米酒', '麻油', '冰糖'],
    instructions: '1. 鸡块热油煎至金黄；2. 加姜蒜爆香倒入酱油米酒麻油各一杯；3. 小火焖20分钟加九层塔翻匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '鸡肉丸子',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鸡胸肉', '马蹄', '葱姜水', '盐', '淀粉', '鸡蛋清'],
    instructions: '1. 鸡胸肉剁泥加马蹄碎葱姜水搅打上劲；2. 团成丸子冷水下锅煮至浮起；3. 加盐调味撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '盐焗鸡翅',
    category: 'meat',
    tags: [],
    ingredients: ['鸡翅中', '盐焗鸡粉', '姜片', '料酒', '食用油'],
    instructions: '1. 鸡翅加盐焗粉姜片料酒腌2小时；2. 锡纸包裹放入烤箱200度烤25分钟；3. 开纸翻面再烤5分钟上色。',
    rating: null,
    history_dates: [],
  },
  {
    name: '梅菜扣肉',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['五花肉', '梅菜', '生抽', '老抽', '料酒', '冰糖', '姜片'],
    instructions: '1. 五花肉煮至筷子能插入切厚片；2. 抹老抽炸至虎皮；3. 梅菜炒香铺碗底码肉片浇调料汁；4. 上锅蒸90分钟倒扣。',
    rating: null,
    history_dates: [],
  },
  {
    name: '东坡肉',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['五花肉', '生抽', '老抽', '料酒', '冰糖', '姜葱', '八角'],
    instructions: '1. 五花肉切大方块焯水；2. 砂锅底铺葱姜放肉块；3. 加生抽老抽料酒冰糖和少量水；4. 小火慢炖2小时至酥烂。',
    rating: null,
    history_dates: [],
  },
  {
    name: '小炒肉',
    category: 'meat',
    tags: [],
    ingredients: ['五花肉', '青椒', '红椒', '蒜末', '豆豉', '生抽', '料酒'],
    instructions: '1. 五花肉切薄片煸出油；2. 加豆豉蒜末炒香；3. 下青红椒大火翻炒；4. 调生抽料酒炒匀出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '猪肉炖粉条',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['五花肉', '粉条', '白菜', '生抽', '老抽', '八角', '姜片'],
    instructions: '1. 五花肉切块煸炒出油；2. 加调料翻炒上色加水炖20分钟；3. 下泡软粉条和白菜炖10分钟至入味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '糯米排骨',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['猪小排', '糯米', '生抽', '老抽', '料酒', '姜末', '葱花'],
    instructions: '1. 糯米浸泡4小时；2. 排骨加调料腌制1小时；3. 裹匀糯米放蒸屉；4. 大火蒸60分钟撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '水煮牛肉',
    category: 'meat',
    tags: [TAGS.SPICY],
    ingredients: ['牛里脊', '豆芽', '莴笋', '豆瓣酱', '干辣椒', '花椒', '蒜末', '淀粉'],
    instructions: '1. 牛肉片加淀粉蛋清上浆；2. 蔬菜焯水垫碗底；3. 豆瓣酱炒红油加水烧开下牛肉煮熟倒入碗中；4. 撒蒜末辣椒花椒淋热油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '酱牛肉',
    category: 'meat',
    tags: [TAGS.COLD_DISH, TAGS.ELDERLY_FRIENDLY],
    ingredients: ['牛腱子', '生抽', '老抽', '料酒', '八角', '桂皮', '香叶', '冰糖', '姜葱'],
    instructions: '1. 牛腱子冷水浸泡2小时去血水；2. 焯水后加全部调料和水大火烧开；3. 转小火卤2小时关火浸泡至凉切片。',
    rating: null,
    history_dates: [],
  },
  {
    name: '黑椒牛柳',
    category: 'meat',
    tags: [],
    ingredients: ['牛里脊', '洋葱', '青椒', '黑胡椒碎', '蚝油', '生抽', '淀粉'],
    instructions: '1. 牛肉切条加生抽淀粉腌制；2. 热油快炒牛柳至变色盛出；3. 爆香洋葱青椒回锅加黑椒蚝油翻炒。',
    rating: null,
    history_dates: [],
  },
  {
    name: '牛肉丸子',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['牛肉馅', '洋葱碎', '鸡蛋', '面包糠', '盐', '黑胡椒', '生抽'],
    instructions: '1. 牛肉馅加洋葱碎蛋液面包糠调料搅打上劲；2. 团成丸子；3. 平底锅煎至四面金黄焖熟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '红烧带鱼',
    category: 'meat',
    tags: [],
    ingredients: ['带鱼', '生抽', '老抽', '料酒', '醋', '糖', '葱姜蒜', '淀粉'],
    instructions: '1. 带鱼切段裹薄淀粉煎至两面金黄；2. 爆香葱姜蒜加生抽老抽料酒糖醋和水；3. 中火烧10分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '水煮鱼',
    category: 'meat',
    tags: [TAGS.SPICY],
    ingredients: ['草鱼片', '豆芽', '豆瓣酱', '干辣椒', '花椒', '蒜末', '蛋清', '淀粉'],
    instructions: '1. 鱼片加蛋清淀粉上浆；2. 豆芽焯水垫底；3. 豆瓣酱炒红油加水烧开下鱼片煮熟；4. 连汤倒入撒蒜末辣椒花椒淋热油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '白灼虾',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鲜虾', '姜片', '葱段', '料酒', '生抽', '姜丝', '香油'],
    instructions: '1. 水加姜片葱段料酒烧开；2. 下虾煮至变红捞出过冰水；3. 配姜丝生抽香油蘸料食用。',
    rating: null,
    history_dates: [],
  },
  {
    name: '油焖大虾',
    category: 'meat',
    tags: [],
    ingredients: ['大虾', '番茄酱', '生抽', '料酒', '糖', '葱姜蒜'],
    instructions: '1. 大虾开背去虾线；2. 热油煎至两面变红；3. 加葱姜蒜爆香倒入番茄酱生抽糖料酒；4. 中火收汁至浓稠。',
    rating: null,
    history_dates: [],
  },
  {
    name: '番茄鱼片',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['龙利鱼', '番茄', '番茄酱', '姜片', '蛋清', '淀粉', '盐', '葱花'],
    instructions: '1. 鱼片加蛋清淀粉腌制；2. 番茄炒出沙加番茄酱和水煮开；3. 下鱼片轻轻推散煮2分钟调味撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜蓉蒸虾',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鲜虾', '蒜末', '粉丝', '生抽', '蒸鱼豉油', '葱花', '食用油'],
    instructions: '1. 虾开背去虾线摆盘；2. 粉丝泡软铺底；3. 蒜末炒香铺在虾上；4. 大火蒸6分钟淋豉油和热油撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '红烧羊肉',
    category: 'meat',
    tags: [TAGS.WINTER_RECOMMENDED],
    ingredients: ['羊腿肉', '生抽', '老抽', '料酒', '冰糖', '八角', '桂皮', '姜葱'],
    instructions: '1. 羊肉切块冷水焯去膻味；2. 炒糖色下羊肉上色；3. 加调料香料和热水大火烧开；4. 转小火炖60分钟至软烂收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '孜然羊肉',
    category: 'meat',
    tags: [TAGS.SPICY],
    ingredients: ['羊肉片', '孜然粒', '孜然粉', '辣椒粉', '洋葱', '生抽', '料酒'],
    instructions: '1. 羊肉片加生抽料酒腌制；2. 热油爆炒洋葱下羊肉大火快炒；3. 撒孜然粒孜然粉辣椒粉翻匀出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜苗炒腊肉',
    category: 'meat',
    tags: [],
    ingredients: ['腊肉', '蒜苗', '干辣椒', '生抽', '料酒', '姜片'],
    instructions: '1. 腊肉切薄片焯水去咸味；2. 蒜苗切段；3. 热油煸腊肉至透明；4. 加姜辣椒蒜苗大火炒断生调味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '花菜炒肉片',
    category: 'meat',
    tags: [],
    ingredients: ['花菜', '猪肉片', '蒜末', '生抽', '蚝油', '料酒', '淀粉'],
    instructions: '1. 花菜掰小朵焯水；2. 肉片加生抽料酒淀粉腌制；3. 热油滑炒肉片盛出；4. 爆蒜下花菜回锅肉片加蚝油翻炒。',
    rating: null,
    history_dates: [],
  },
  {
    name: '糖醋里脊',
    category: 'meat',
    tags: [],
    ingredients: ['猪里脊', '番茄酱', '白糖', '白醋', '生抽', '淀粉', '面粉', '鸡蛋'],
    instructions: '1. 里脊切条加蛋液淀粉面粉挂糊；2. 油温六成炸至金黄复炸一次；3. 锅中番茄酱糖醋生抽烧开勾芡倒入里脊翻匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '香干炒肉',
    category: 'meat',
    tags: [],
    ingredients: ['香干', '猪肉片', '青椒', '蒜末', '生抽', '蚝油', '料酒'],
    instructions: '1. 香干切片猪肉切片腌制；2. 热油滑肉片盛出；3. 爆蒜下香干青椒翻炒；4. 回锅肉片加生抽蚝油炒匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '腐乳肉',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['五花肉', '红腐乳', '腐乳汁', '料酒', '糖', '姜片', '葱段'],
    instructions: '1. 五花肉切厚片焯水；2. 腐乳碾碎加腐乳汁料酒糖调汁；3. 肉片码碗中浇汁；4. 上锅大火蒸90分钟倒扣。',
    rating: null,
    history_dates: [],
  },
  {
    name: '红烧猪蹄',
    category: 'meat',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['猪蹄', '生抽', '老抽', '冰糖', '八角', '桂皮', '料酒', '姜葱'],
    instructions: '1. 猪蹄剁块焯水洗净；2. 炒糖色下猪蹄翻炒上色；3. 加调料香料和热水大火烧开；4. 高压锅压30分钟至软烂收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '干锅鸡',
    category: 'meat',
    tags: [TAGS.SPICY],
    ingredients: ['鸡腿肉', '土豆', '洋葱', '干辣椒', '花椒', '豆瓣酱', '生抽', '料酒'],
    instructions: '1. 鸡块加料酒生抽腌制；2. 土豆切片炸至金黄；3. 鸡块煎至焦香加豆瓣酱辣椒花椒炒香；4. 加土豆洋葱干锅翻炒收汁。',
    rating: null,
    history_dates: [],
  },

  // ============== 素菜 (veg) - 61 道 ==============
  {
    name: '清炒时蔬',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['当季绿叶菜', '蒜末', '盐', '食用油'],
    instructions: '1. 蔬菜洗净沥干；2. 热锅热油爆香蒜末；3. 大火快炒至断生；4. 加盐翻匀出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜蓉西兰花',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['西兰花', '蒜末', '盐', '蚝油', '食用油'],
    instructions: '1. 西兰花掰小朵盐水浸泡；2. 沸水加盐油焯 1 分钟过凉；3. 热油爆蒜；4. 下西兰花加蚝油盐快炒。',
    rating: null,
    history_dates: [],
  },
  {
    name: '凉拌黄瓜',
    category: 'veg',
    tags: [TAGS.COLD_DISH, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['黄瓜', '蒜末', '生抽', '香醋', '香油', '糖', '小米椒'],
    instructions: '1. 黄瓜拍碎切段；2. 撒盐腌 10 分钟挤水；3. 加蒜末生抽醋糖香油；4. 拌匀冷藏 10 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '醋溜白菜',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['白菜帮', '干辣椒', '蒜片', '醋', '生抽', '糖', '淀粉水'],
    instructions: '1. 白菜帮斜刀切片；2. 调醋糖生抽汁；3. 热油爆辣椒蒜片；4. 下白菜大火快炒；5. 倒汁勾薄芡。',
    rating: null,
    history_dates: [],
  },
  {
    name: '干煸豆角',
    category: 'veg',
    tags: [],
    ingredients: ['四季豆', '肉末', '榨菜', '蒜末', '干辣椒', '生抽', '盐'],
    instructions: '1. 豆角去筋掐段；2. 油锅煸至虎皮捞出；3. 爆香蒜辣椒下肉末榨菜炒香；4. 倒入豆角调味翻炒。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜蓉空心菜',
    category: 'veg',
    tags: [],
    ingredients: ['空心菜', '蒜末', '盐', '食用油'],
    instructions: '1. 空心菜掐段洗净；2. 热油爆蒜末；3. 大火下空心菜快炒；4. 加盐迅速翻匀出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '凉拌木耳',
    category: 'veg',
    tags: [TAGS.COLD_DISH, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['黑木耳', '彩椒', '蒜末', '香醋', '生抽', '香油', '糖', '小米椒'],
    instructions: '1. 木耳泡发洗净；2. 沸水焯 2 分钟过凉；3. 彩椒切丝；4. 加蒜末调味料拌匀；5. 冷藏 15 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '番茄炒蛋',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['番茄', '鸡蛋', '葱花', '盐', '糖'],
    instructions: '1. 番茄去皮切块；2. 鸡蛋打散加盐；3. 热油炒蛋盛出；4. 番茄炒出沙加糖；5. 回锅鸡蛋翻匀撒葱。',
    rating: null,
    history_dates: [],
  },
  {
    name: '麻婆豆腐',
    category: 'veg',
    tags: [TAGS.SPICY],
    ingredients: ['嫩豆腐', '牛肉末', '豆瓣酱', '豆豉', '花椒粉', '蒜末', '葱花', '淀粉水'],
    instructions: '1. 豆腐切丁焯水；2. 牛肉末炒香；3. 加豆瓣酱豆豉炒红油；4. 加水下豆腐煮 5 分钟；5. 勾芡撒花椒粉葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '拍黄瓜',
    category: 'veg',
    tags: [TAGS.COLD_DISH, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['黄瓜', '蒜末', '香醋', '生抽', '香油', '盐', '糖'],
    instructions: '1. 黄瓜拍裂切段；2. 加盐腌 10 分钟挤水；3. 加蒜末和调料拌匀；4. 冷藏入味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '清炒莴笋丝',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['莴笋', '蒜末', '盐', '食用油'],
    instructions: '1. 莴笋去皮切丝；2. 加盐抓匀腌 5 分钟挤水；3. 热油爆蒜；4. 下莴笋丝大火快炒断生。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜炒菜心',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['菜心', '蒜末', '盐', '蚝油', '食用油'],
    instructions: '1. 菜心去老叶洗净；2. 沸水焯 30 秒过凉；3. 热油爆蒜；4. 下菜心炒匀加蚝油盐。',
    rating: null,
    history_dates: [],
  },
  {
    name: '地三鲜',
    category: 'veg',
    tags: [],
    ingredients: ['茄子', '土豆', '青椒', '蒜末', '生抽', '老抽', '糖', '淀粉水'],
    instructions: '1. 茄子土豆切滚刀块；2. 油温七成炸土豆至金黄捞出；3. 炸茄子至软捞出；4. 锅留底油爆香蒜末下青椒；5. 回锅茄子土豆调味勾薄芡。',
    rating: null,
    history_dates: [],
  },
  {
    name: '酸辣土豆丝',
    category: 'veg',
    tags: [TAGS.SPICY],
    ingredients: ['土豆', '干辣椒', '花椒', '蒜末', '白醋', '生抽', '盐'],
    instructions: '1. 土豆切丝凉水浸洗去淀粉；2. 热油爆香花椒干辣椒蒜末；3. 下土豆丝大火快炒；4. 淋白醋加生抽盐翻匀；5. 出锅前再淋几滴醋。',
    rating: null,
    history_dates: [],
  },
  {
    name: '虎皮青椒',
    category: 'veg',
    tags: [TAGS.SPICY],
    ingredients: ['青椒', '蒜末', '生抽', '香醋', '糖', '盐'],
    instructions: '1. 青椒去蒂拍扁；2. 少油中小火煎至两面起虎皮；3. 下蒜末爆香；4. 调生抽醋糖盐汁倒入；5. 烧至汁收浓。',
    rating: null,
    history_dates: [],
  },
  {
    name: '烧茄子',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['茄子', '肉末', '蒜末', '生抽', '老抽', '糖', '淀粉水', '葱花'],
    instructions: '1. 茄子切条拍淀粉；2. 油锅过油捞出油；3. 肉末蒜末炒香；4. 加生抽老抽糖水烧开；5. 下茄子烧入味勾薄芡撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '上汤娃娃菜',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['娃娃菜', '皮蛋', '咸蛋黄', '蒜末', '高汤', '枸杞', '盐'],
    instructions: '1. 娃娃菜纵切三瓣焯水摆盘；2. 皮蛋咸蛋黄切块；3. 热油爆香蒜末下蛋末炒香；4. 加高汤烧开调盐；5. 浇在娃娃菜上撒枸杞。',
    rating: null,
    history_dates: [],
  },
  {
    name: '白菜炖豆腐',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['白菜', '北豆腐', '虾皮', '姜片', '生抽', '盐', '香油'],
    instructions: '1. 白菜手撕块；2. 豆腐切块焯水；3. 热油爆姜下虾皮炒香；4. 下白菜炒软加豆腐生抽和水；5. 加盖炖 10 分钟调盐淋香油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '凉拌三丝',
    category: 'veg',
    tags: [TAGS.COLD_DISH, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['黄瓜', '胡萝卜', '土豆', '蒜末', '香醋', '生抽', '香油', '糖'],
    instructions: '1. 土豆胡萝卜切丝焯水过凉；2. 黄瓜切丝；3. 三丝合盘加蒜末；4. 加生抽醋糖香油拌匀；5. 冷藏 15 分钟入味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '香菇青菜',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['香菇', '上海青', '蒜末', '蚝油', '生抽', '盐', '淀粉水'],
    instructions: '1. 上海青沸水焯软摆盘；2. 香菇切片；3. 热油爆蒜下香菇炒香；4. 加生抽蚝油盐和少量水；5. 勾薄芡浇在青菜上。',
    rating: null,
    history_dates: [],
  },
  {
    name: '干锅菜花',
    category: 'veg',
    tags: [],
    ingredients: ['菜花', '五花肉', '干辣椒', '蒜末', '生抽', '蚝油', '豆瓣酱'],
    instructions: '1. 菜花掰小朵干锅煸至表面焦香捞出；2. 五花肉切薄片煸出油；3. 加蒜干辣椒豆瓣酱炒香；4. 下菜花翻炒；5. 加生抽蚝油调味出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '番茄烧土豆',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['番茄', '土豆', '蒜末', '生抽', '糖', '盐', '葱花'],
    instructions: '1. 土豆切片微炸至两面金黄；2. 番茄去皮切块热油炒出沙；3. 加蒜末糖生抽烧开；4. 下土豆片烧 5 分钟入味；5. 调盐撒葱花。',
    rating: null,
    history_dates: [],
  },
  
  // ============== 新增素菜 (veg) - 39 道 ==============
  {
    name: '红烧豆腐',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['北豆腐', '生抽', '老抽', '糖', '蒜末', '葱花', '淀粉水'],
    instructions: '1. 豆腐切块煎至两面金黄；2. 加蒜末生抽老抽糖和少量水烧5分钟；3. 勾薄芡撒葱花出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '煎豆腐',
    category: 'veg',
    tags: [],
    ingredients: ['北豆腐', '食用油', '盐', '黑胡椒', '生抽'],
    instructions: '1. 豆腐切厚片拍干水分；2. 平底锅少油小火煎至两面金黄；3. 撒盐黑胡椒淋生抽出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '小葱拌豆腐',
    category: 'veg',
    tags: [TAGS.COLD_DISH, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['内脂豆腐', '小葱', '香油', '生抽', '盐'],
    instructions: '1. 豆腐切块摆盘；2. 小葱切花撒在豆腐上；3. 淋香油生抽加盐拌匀即可。',
    rating: null,
    history_dates: [],
  },
  {
    name: '家常豆腐',
    category: 'veg',
    tags: [],
    ingredients: ['北豆腐', '青椒', '豆瓣酱', '蒜末', '生抽', '淀粉水'],
    instructions: '1. 豆腐切三角片煎至金黄；2. 爆香蒜末豆瓣酱加青椒；3. 下豆腐加生抽和少量水烧3分钟勾芡。',
    rating: null,
    history_dates: [],
  },
  {
    name: '铁板豆腐',
    category: 'veg',
    tags: [],
    ingredients: ['北豆腐', '洋葱', '青椒', '豆瓣酱', '蒜末', '生抽', '食用油'],
    instructions: '1. 豆腐切片煎至两面焦黄；2. 爆香蒜末豆瓣酱加洋葱青椒；3. 回锅豆腐大火翻炒调味出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '酿豆腐',
    category: 'veg',
    tags: [],
    ingredients: ['北豆腐', '猪肉馅', '香菇', '胡萝卜', '生抽', '淀粉', '蒜末'],
    instructions: '1. 豆腐对切挖小洞；2. 肉馅加香菇碎胡萝卜碎调味酿入；3. 煎至底部金黄加水焖熟勾芡。',
    rating: null,
    history_dates: [],
  },
  {
    name: '豆腐煲',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['北豆腐', '白菜', '粉丝', '生抽', '老抽', '蒜末', '姜片'],
    instructions: '1. 豆腐煎至金黄切块；2. 砂锅底铺白菜粉丝加豆腐；3. 加生抽老抽蒜末姜片和水焖煮15分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜蓉青菜',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['小油菜', '蒜末', '盐', '食用油'],
    instructions: '1. 小油菜洗净汥干；2. 热油爆香蒜末；3. 大火下青菜快炒至断生加盐出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '炝炒油麦菜',
    category: 'veg',
    tags: [],
    ingredients: ['油麦菜', '干辣椒', '蒜片', '盐', '食用油'],
    instructions: '1. 油麦菜洗净切段；2. 热油爆香干辣椒蒜片；3. 大火下油麦菜快炒加盐出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '上汤菠菜',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['菠菜', '皮蛋', '蒜末', '高汤', '盐', '香油'],
    instructions: '1. 菠菜焯水摆盘；2. 热油爆香蒜末加皮蛋碎和高汤烧开；3. 调盐浇在菠菜上淋香油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '白灰芥兰',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['芥兰', '蒜末', '蚝油', '盐', '食用油'],
    instructions: '1. 芥兰切段沛水加盐油焯2分钟过凉；2. 摆盘；3. 淋蚝油蒜末和热油即可。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜蓉生菜',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['生菜', '蒜末', '蚝油', '盐', '食用油'],
    instructions: '1. 生菜洗净汥干；2. 热油爆香蒜末；3. 大火下生菜快炒加蚝油盐翻匀出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '清炒丝瓜',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['丝瓜', '蒜末', '盐', '食用油'],
    instructions: '1. 丝瓜去皮切满刀片；2. 热油爆蒜末；3. 下丝瓜大火快炒至透明加盐出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '丝瓜炒蛋',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['丝瓜', '鸡蛋', '蒜末', '盐', '食用油'],
    instructions: '1. 丝瓜去皮切片；2. 热油炒蛋盛出；3. 爆蒜下丝瓜炒软回锅蛋加盐翻匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '丝瓜虾皮',
    category: 'veg',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['丝瓜', '虾皮', '蒜末', '盐', '生抽', '食用油'],
    instructions: '1. 丝瓜去皮切滞刀块；2. 热油爆蒜末虾皮炒香；3. 下丝瓜翻炒加盐生抽炒至熟透。',
    rating: null,
    history_dates: [],
  },
  {
    name: '红烧茄子',
    category: 'veg',
    tags: [],
    ingredients: ['茄子', '生抽', '老抽', '糖', '蒜末', '淀粉水', '葱花'],
    instructions: '1. 茄子切滞刀块拍薄淀粉；2. 过油至微软捞出；3. 爆蒜加生抽老抽糖水烧开下茄子烧3分钟勾芡撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '鱼香茄子',
    category: 'veg',
    tags: [],
    ingredients: ['茄子', '泡椒', '蒜末', '姜末', '葱花', '糖', '醋', '生抽', '淀粉水'],
    instructions: '1. 茄子切条过油或干煎至软；2. 调鱼香汁(糖醋生抽淀粉水)；3. 爆香泡椒蒜姜下茄子倒汁翻炒收汁撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜泥茄子',
    category: 'veg',
    tags: [TAGS.COLD_DISH, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['茄子', '蒜末', '生抽', '香醋', '香油', '盐', '小米椒'],
    instructions: '1. 茄子整条蒸熟撕成条状；2. 加蒜末生抽醋香油小米椒拌匀；3. 冷藏15分钟入味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '茄子煲',
    category: 'veg',
    tags: [],
    ingredients: ['茄子', '五花肉', '蒜末', '生抽', '老抽', '糖', '砂锅'],
    instructions: '1. 茄子切滞刀块过油；2. 五花肉炒香加蒜末豆瓣酱；3. 下茄子加调料和水砂锅焖煮15分钟收汁。',
    rating: null,
    history_dates: [],
  },
  {
    name: '土豆泥',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['土豆', '黄油', '牛奶', '盐', '黑胡椒'],
    instructions: '1. 土豆去皮切块蒸熟；2. 压成泥加黄油牛奶盐拌匀；3. 撑上黑胡椒即可。',
    rating: null,
    history_dates: [],
  },
  {
    name: '干锅土豆片',
    category: 'veg',
    tags: [],
    ingredients: ['土豆', '五花肉', '干辣椒', '蒜末', '生抽', '葱花'],
    instructions: '1. 土豆切片油煎至两面金黄；2. 五花肉片煸香加干辣椒蒜末；3. 回锅土豆加生抽大火翻炒撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '炝炒土豆丝',
    category: 'veg',
    tags: [],
    ingredients: ['土豆', '干辣椒', '花椒', '蒜末', '白醋', '盐'],
    instructions: '1. 土豆切细丝浸洗去淀粉；2. 热油爆花椒干辣椒蒜末；3. 大火快炒土豆丝淋醋加盐翻匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜蓉四季豆',
    category: 'veg',
    tags: [],
    ingredients: ['四季豆', '蒜末', '盐', '生抽', '食用油'],
    instructions: '1. 四季豆掉去两头折段焯水；2. 热油爆香蒜末；3. 下四季豆大火翻炒加生抽盐炒熟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '豆角炒茄子',
    category: 'veg',
    tags: [],
    ingredients: ['豆角', '茄子', '蒜末', '生抽', '老抽', '盐'],
    instructions: '1. 豆角折段茄子切滞刀块；2. 热油先炒豆角再下茄子；3. 加蒜末生抽老抽盐和少量水焖至熟透。',
    rating: null,
    history_dates: [],
  },
  {
    name: '黄瓜炒蛋',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['黄瓜', '鸡蛋', '盐', '葱花', '食用油'],
    instructions: '1. 黄瓜切片鸡蛋打散；2. 热油炒蛋盛出；3. 下黄瓜片翻炒回锅蛋加盐翻匀撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '白灠西兰花',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['西兰花', '蒜末', '蚝油', '盐', '食用油'],
    instructions: '1. 西兰花掰小朵沛水加盐油焯2分钟；2. 捞出汥干摆盘；3. 淋蚝油蒜末和热油即可。',
    rating: null,
    history_dates: [],
  },
  {
    name: '西兰花炒虾仁',
    category: 'veg',
    tags: [],
    ingredients: ['西兰花', '虾仁', '蒜末', '盐', '料酒', '淀粉', '食用油'],
    instructions: '1. 虾仁加料酒淀粉腌制；2. 西兰花焯水；3. 热油滑炒虾仁爆蒜下西兰花加盐翻炒出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '手撕包菜',
    category: 'veg',
    tags: [],
    ingredients: ['包菜', '干辣椒', '蒜末', '生抽', '醋', '盐', '食用油'],
    instructions: '1. 包菜手撕块状；2. 热油爆干辣椒蒜末；3. 大火下包菜快炒加生抽醋盐翻匀出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '酸辣白菜',
    category: 'veg',
    tags: [TAGS.SPICY],
    ingredients: ['白菜帮', '干辣椒', '花椒', '蒜片', '醋', '生抽', '糖', '盐'],
    instructions: '1. 白菜帮斜切片；2. 热油爆花椒干辣椒蒜片；3. 大火下白菜快炒淋醋加生抽糖盐翻匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '干锅茶树菇',
    category: 'veg',
    tags: [],
    ingredients: ['茶树菇', '五花肉', '干辣椒', '蒜末', '生抽', '蚝油', '葱花'],
    instructions: '1. 茶树菇泡发撕小条焯水；2. 五花肉煸香加干辣椒蒜末；3. 下茶树菇大火翻炒加生抽蚝油撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '清炒杏鲍菇',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['杏鲍菇', '蒜末', '盐', '生抽', '食用油'],
    instructions: '1. 杏鲍菇切片；2. 热油爆蒜末；3. 下杏鲍菇中火煎炒至微焦加盐生抽翻匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒜炒香菇',
    category: 'veg',
    tags: [],
    ingredients: ['香菇', '蒜末', '生抽', '蚝油', '盐', '葱花'],
    instructions: '1. 香菇分切两半；2. 热油爆香蒜末下香菇煎炒；3. 加生抽蚝油盐翻炒至熟撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '小炒金针菇',
    category: 'veg',
    tags: [],
    ingredients: ['金针菇', '青椒', '蒜末', '生抽', '盐', '食用油'],
    instructions: '1. 金针菇去根撕小把焯水；2. 热油爆蒜加青椒丝；3. 下金针菇大火翻炒加生抽盐炒匀。',
    rating: null,
    history_dates: [],
  },
  {
    name: '油焖茄子',
    category: 'veg',
    tags: [],
    ingredients: ['茄子', '生抽', '老抽', '糖', '蒜末', '葱花', '食用油'],
    instructions: '1. 茄子切条不断；2. 热油煎至两面微软；3. 加蒜末生抽老抽糖和少量水加盖焖煮5分钟收汁撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '番茄烧豆腐',
    category: 'veg',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['北豆腐', '番茄', '蒜末', '生抽', '糖', '盐', '葱花'],
    instructions: '1. 豆腐切块煎至金黄；2. 番茄热油炒出沙加蒜末；3. 加水生抽糖烧开下豆腐烧5分钟调盐撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '韭菜炒蛋',
    category: 'veg',
    tags: [],
    ingredients: ['韭菜', '鸡蛋', '盐', '食用油'],
    instructions: '1. 韭菜洗净切段鸡蛋打散；2. 热油炒蛋盛出；3. 下韭菜大火快炒回锅蛋加盐翻匀出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '芹菜花生',
    category: 'veg',
    tags: [TAGS.COLD_DISH, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['芹菜', '花生米', '香油', '生抽', '盐', '糖'],
    instructions: '1. 花生米煮熟去皮；2. 芹菜切丁焯水过凉；3. 加花生淋香油生抽盐糖拌匀冷藏。',
    rating: null,
    history_dates: [],
  },
  {
    name: '凉拌海带丝',
    category: 'veg',
    tags: [TAGS.COLD_DISH, TAGS.SUMMER_RECOMMENDED],
    ingredients: ['海带丝', '蒜末', '小米椒', '生抽', '香醋', '香油', '糖', '白苝麻'],
    instructions: '1. 海带丝泡发洗净焯水3分钟过凉；2. 加蒜末小米椒生抽醋香油糖拌匀；3. 撒白苝麻冷藏入味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '莴笋炒片',
    category: 'veg',
    tags: [],
    ingredients: ['莴笋', '胡萝卜', '木耳', '蒜末', '盐', '生抽', '食用油'],
    instructions: '1. 莴笋去皮切薄片胡萝卜切片木耳泡发；2. 热油爆蒜下莴笋胡萝卜木耳；3. 大火翻炒加盐生抽炒断生。',
    rating: null,
    history_dates: [],
  },

  // ============== 汤 (soup) - 24 道 ==============
  {
    name: '排骨冬瓜汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['猪肋排', '冬瓜', '姜片', '葱段', '盐', '料酒'],
    instructions: '1. 排骨焯水洗净；2. 加姜葱料酒和水大火烧开；3. 转小火炖 40 分钟；4. 加冬瓜再炖 15 分钟；5. 加盐调味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '紫菜蛋花汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['紫菜', '鸡蛋', '虾皮', '葱花', '香油', '盐', '生抽'],
    instructions: '1. 紫菜虾皮入碗加生抽香油；2. 锅中烧开水；3. 淋入打散蛋液成蛋花；4. 加盐冲入碗中撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '番茄蛋汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['番茄', '鸡蛋', '葱花', '盐', '香油', '淀粉水'],
    instructions: '1. 番茄去皮切块；2. 锅中煸炒出沙加水烧开；3. 调味勾薄芡；4. 淋蛋液成蛋花；5. 撒葱花淋香油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '山药排骨汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY, TAGS.WINTER_RECOMMENDED],
    ingredients: ['排骨', '铁棍山药', '枸杞', '姜片', '盐', '料酒'],
    instructions: '1. 排骨焯水；2. 加姜片料酒水大火烧开；3. 小火炖 40 分钟；4. 加山药再炖 20 分钟；5. 撒枸杞加盐。',
    rating: null,
    history_dates: [],
  },
  {
    name: '玉米排骨汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['排骨', '甜玉米', '胡萝卜', '姜片', '盐', '料酒'],
    instructions: '1. 排骨焯水洗净；2. 加姜片料酒水烧开；3. 小火炖 40 分钟；4. 加玉米胡萝卜炖 20 分钟；5. 加盐。',
    rating: null,
    history_dates: [],
  },
  {
    name: '萝卜牛腩汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY, TAGS.WINTER_RECOMMENDED],
    ingredients: ['牛腩', '白萝卜', '姜片', '葱段', '料酒', '盐', '白胡椒粉'],
    instructions: '1. 牛腩焯水切块；2. 加姜葱料酒水大火烧开；3. 小火炖 90 分钟；4. 加萝卜炖 20 分钟；5. 加盐和白胡椒。',
    rating: null,
    history_dates: [],
  },
  {
    name: '绿豆南瓜汤',
    category: 'soup',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['绿豆', '南瓜', '冰糖', '清水'],
    instructions: '1. 绿豆浸泡 2 小时；2. 冷水下锅大火煮开；3. 转小火煮 30 分钟至开花；4. 加南瓜块再煮 15 分钟；5. 加冰糖。',
    rating: null,
    history_dates: [],
  },
  {
    name: '冰镇银耳羹',
    category: 'soup',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['银耳', '红枣', '枸杞', '冰糖', '清水'],
    instructions: '1. 银耳泡发撕小朵；2. 加水大火烧开；3. 转小火炖 1 小时出胶；4. 加红枣冰糖再煮 10 分钟；5. 放凉冷藏。',
    rating: null,
    history_dates: [],
  },
  {
    name: '丝瓜蛋花汤',
    category: 'soup',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['丝瓜', '鸡蛋', '姜丝', '盐', '香油'],
    instructions: '1. 丝瓜去皮切滚刀块；2. 热油爆姜丝下丝瓜炒软；3. 加水烧开；4. 淋入蛋液成蛋花；5. 加盐淋香油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '冬瓜薏米汤',
    category: 'soup',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['冬瓜', '薏米', '排骨', '姜片', '盐'],
    instructions: '1. 薏米浸泡 2 小时；2. 排骨焯水；3. 加薏米姜片水炖 60 分钟；4. 加冬瓜再炖 20 分钟；5. 加盐。',
    rating: null,
    history_dates: [],
  },
  {
    name: '西湖牛肉羹',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['牛肉末', '嫩豆腐', '鸡蛋清', '香菜', '姜末', '淀粉水', '盐', '胡椒粉'],
    instructions: '1. 牛肉末加姜末淀粉搅匀；2. 豆腐切小丁焯水；3. 锅中添水烧开下牛肉末豆腐丁；4. 调盐胡椒勾浓芡；5. 淋蛋清成蛋花撒香菜末。',
    rating: null,
    history_dates: [],
  },
  {
    name: '酸辣汤',
    category: 'soup',
    tags: [],
    ingredients: ['豆腐丝', '木耳丝', '胡萝卜丝', '鸡蛋', '香醋', '白胡椒粉', '生抽', '淀粉水', '香油'],
    instructions: '1. 豆腐木耳胡萝卜切丝；2. 锅中加高汤烧开下三丝；3. 加生抽胡椒粉调味；4. 勾薄芡淋蛋液；5. 出锅前加香醋淋香油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '莲藕排骨汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['排骨', '莲藕', '姜片', '料酒', '盐'],
    instructions: '1. 排骨焯水洗净；2. 莲藕切滚刀块；3. 加姜片料酒和足量水烧开；4. 转小火炖 90 分钟；5. 加盐调味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '银耳红枣汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['银耳', '红枣', '枸杞', '冰糖', '清水'],
    instructions: '1. 银耳泡发撕小朵；2. 加足量水大火烧开；3. 转小火炖 60 分钟出胶；4. 加红枣冰糖再煮 15 分钟；5. 撒枸杞。',
    rating: null,
    history_dates: [],
  },
  {
    name: '鲫鱼豆腐汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['鲫鱼', '嫩豆腐', '姜片', '葱段', '料酒', '盐', '白胡椒粉', '食用油'],
    instructions: '1. 鲫鱼收拾净抹干；2. 热油煎鱼两面金黄；3. 加姜片料酒和热水大火烧开；4. 炸出奶白色汤下豆腐；5. 炖 10 分钟加盐胡椒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '菌菇鸡汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY, TAGS.WINTER_RECOMMENDED],
    ingredients: ['老母鸡', '香菇', '口蘑', '茶树菇', '姜片', '枸杞', '料酒', '盐'],
    instructions: '1. 鸡块焯水洗净；2. 菇类泡发洗净；3. 加姜片料酒和水大火烧开；4. 转小火炖 90 分钟；5. 加菇类枸杞再炖 20 分钟调盐。',
    rating: null,
    history_dates: [],
  },
  {
    name: '金针菇蛋汤',
    category: 'soup',
    tags: [],
    ingredients: ['金针菇', '鸡蛋', '番茄', '葱花', '盐', '香油', '生抽'],
    instructions: '1. 金针菇去根净洗；2. 番茄去皮切块热油炒出沙；3. 加水烧开下金针菇；4. 淋入蛋液成蛋花；5. 调生抽盐香油撒葱花。',
    rating: null,
    history_dates: [],
  },
  
  {
    name: '苦瓜排骨汤',
    category: 'soup',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['排骨', '苦瓜', '黄豆', '姜片', '盐', '料酒'],
    instructions: '1. 排骨焯水；2. 苦瓜去瓤切块焯去苦味；3. 加黄豆姜片料酒和水烧开；4. 小火炖 60 分钟；5. 加苦瓜再炖 20 分钟加盐。',
    rating: null,
    history_dates: [],
  },

  // ============== 新增汤 (soup) - 6 道 ==============
  {
    name: '三鲜汤',
    category: 'soup',
    tags: [],
    ingredients: ['虾仁', '鸡蛋', '番茄', '豆腐', '葱花', '盐', '香油'],
    instructions: '1. 番茄切块豆腐切丁；2. 水烧开下番茄豆腐煮5分钟；3. 加虾仁煮熟淋蛋液调盐撒葱花淋香油。',
    rating: null,
    history_dates: [],
  },
  {
    name: '海带排骨汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['排骨', '海带', '姜片', '料酒', '盐', '葱花'],
    instructions: '1. 排骨焯水洗净；2. 加姜片料酒和水大火烧开转小火炖40分钟；3. 加海带结再炖15分钟加盐撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '白萝卜羊肉汤',
    category: 'soup',
    tags: [TAGS.WINTER_RECOMMENDED],
    ingredients: ['羊肉', '白萝卜', '姜片', '葱段', '料酒', '盐', '白胡椒粉', '枕杠'],
    instructions: '1. 羊肉切块焯水去膻；2. 加姜葱料酒枕杠和水大火烧开；3. 小火炖60分钟加萝卜再炖20分钟加盐胡椒。',
    rating: null,
    history_dates: [],
  },
  {
    name: '花生猪脚汤',
    category: 'soup',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['猪脚', '花生', '姜片', '料酒', '盐', '红枣'],
    instructions: '1. 猪脚剁块焯水洗净；2. 花生提前浸泡2小时；3. 加姜片料酒红枣和足量水大火烧开；4. 转小火炖90分钟至猪脚软烂加盐。',
    rating: null,
    history_dates: [],
  },
  {
    name: '凉瓜黄豆汤',
    category: 'soup',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['苦瓜', '黄豆', '排骨', '姜片', '盐'],
    instructions: '1. 黄豆提前浸泡4小时；2. 排骨焯水加姜片黄豆和水炖60分钟；3. 加苦瓜再炖20分钟加盐。',
    rating: null,
    history_dates: [],
  },
  {
    name: '绿豆百合汤',
    category: 'soup',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['绿豆', '百合', '冰糖', '清水'],
    instructions: '1. 绿豆浸泡2小时；2. 加水大火煮开转小火煮30分钟至开花；3. 加百合冰糖再煮10分钟放凉可冷藏。',
    rating: null,
    history_dates: [],
  },

  // ============== 常规主食 (staple_normal) - 5 道 ==============
  {
    name: '白米饭',
    category: 'staple_normal',
    tags: [],
    ingredients: ['大米', '清水'],
    instructions: '1. 大米淘洗 2 次；2. 水量没过米一指节；3. 电饭锅煮饭模式；4. 跳闸后焖 10 分钟松散。',
    rating: null,
    history_dates: [],
  },
  {
    name: '杂粮饭',
    category: 'staple_normal',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['大米', '糙米', '燕麦米', '红米', '黑米'],
    instructions: '1. 杂粮提前浸泡 2 小时；2. 与大米按 1:2 混合；3. 水量略多于白米饭；4. 电饭锅煮饭模式；5. 焖 10 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '蒸馒头',
    category: 'staple_normal',
    tags: [],
    ingredients: ['面粉', '酵母', '白糖', '温水'],
    instructions: '1. 发面至两倍大；2. 揉光排气分剂；3. 揉成馒头胚；4. 二次醒发 20 分钟；5. 冷水上锅蒸 15 分钟。',
    rating: null,
    history_dates: [],
  },
  {
    name: '家常烙饼',
    category: 'staple_normal',
    tags: [],
    ingredients: ['面粉', '温水', '盐', '食用油'],
    instructions: '1. 温水加盐和面醒 30 分钟；2. 擀薄片刷油卷起；3. 切剂盘起擀圆；4. 平底锅小火两面烙；5. 出锅抖松。',
    rating: null,
    history_dates: [],
  },
  {
    name: '白米稀饭',
    category: 'staple_normal',
    tags: [TAGS.SUMMER_RECOMMENDED, TAGS.PORRIDGE],
    ingredients: ['大米', '清水'],
    instructions: '1. 大米淘洗加 8 倍水；2. 大火烧开转小火慢熬；3. 期间搅拌防粘底；4. 熬 40 分钟至米花开。',
    rating: null,
    history_dates: [],
  },

  // ============== 一锅出简餐 (staple_onepot) - 5 道 ==============
  {
    name: '番茄鸡蛋面',
    category: 'staple_onepot',
    tags: [],
    ingredients: ['挂面', '番茄', '鸡蛋', '葱花', '盐', '生抽', '香油'],
    instructions: '1. 番茄去皮切块；2. 热油炒蛋盛出；3. 番茄炒出沙加水烧开；4. 下面条煮熟；5. 回锅鸡蛋调味撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '猪肉白菜水饺',
    category: 'staple_onepot',
    tags: [],
    ingredients: ['饺子皮', '猪肉馅', '大白菜', '葱姜', '生抽', '香油', '盐'],
    instructions: '1. 白菜剁碎挤水；2. 与肉馅葱姜调料拌匀；3. 包成饺子；4. 沸水下锅煮 3 沸点冷水；5. 浮起捞出蘸醋。',
    rating: null,
    history_dates: [],
  },
  {
    name: '老北京炸酱面',
    category: 'staple_onepot',
    tags: [],
    ingredients: ['手擀面', '猪肉丁', '黄豆酱', '甜面酱', '葱姜', '黄瓜丝', '豆芽'],
    instructions: '1. 黄豆酱甜面酱调匀；2. 油煸肉丁加葱姜；3. 倒酱小火慢炒 15 分钟；4. 面条煮熟过水；5. 浇酱配菜码。',
    rating: null,
    history_dates: [],
  },
  {
    name: '过桥米线',
    category: 'staple_onepot',
    tags: [],
    ingredients: ['米线', '鸡汤', '鸡肉片', '香菇', '青菜', '鹌鹑蛋', '葱花'],
    instructions: '1. 米线泡软；2. 鸡汤大火烧滚；3. 烫熟肉片香菇青菜；4. 下米线煮 2 分钟；5. 打入鹌鹑蛋撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '麻酱凉面',
    category: 'staple_onepot',
    tags: [TAGS.SUMMER_RECOMMENDED],
    ingredients: ['面条', '芝麻酱', '黄瓜丝', '胡萝卜丝', '蒜泥', '香醋', '生抽', '香油'],
    instructions: '1. 面条煮熟过冰水；2. 芝麻酱用温水澥开；3. 加蒜泥醋生抽香油拌匀；4. 浇面上铺黄瓜胡萝卜丝拌食。',
    rating: null,
    history_dates: [],
  },

  // ============== 新增一锅出简餐 (staple_onepot) - 7 道 ==============
  {
    name: '蛋炒饭',
    category: 'staple_onepot',
    tags: [],
    ingredients: ['米饭', '鸡蛋', '葱花', '盐', '生抽', '食用油'],
    instructions: '1. 鸡蛋打散加盐；2. 热油下蛋液翻炒加米饭大火炒散；3. 加生抽翻炒均匀撒葱花出锅。',
    rating: null,
    history_dates: [],
  },
  {
    name: '葱油拌面',
    category: 'staple_onepot',
    tags: [],
    ingredients: ['面条', '小葱', '生抽', '老抽', '香油', '食用油'],
    instructions: '1. 小葱切段热油炒至焦香成葱油；2. 面条煮熟捞出；3. 加生抽老抽葱油香油拌匀即可。',
    rating: null,
    history_dates: [],
  },
  {
    name: '酸辣粉',
    category: 'staple_onepot',
    tags: [TAGS.SPICY],
    ingredients: ['红薯粉', '花生', '黄豆', '酋菜', '辣椒油', '香醋', '生抽', '蒜末'],
    instructions: '1. 红薯粉泡软；2. 煮水下粉条煮熟捞入碗；3. 加花生酋菜黄豆淋辣椒油醋生抽蒜末调味。',
    rating: null,
    history_dates: [],
  },
  {
    name: '牛肉面',
    category: 'staple_onepot',
    tags: [],
    ingredients: ['面条', '牛腩', '生抽', '老抽', '八角', '姜片', '青菜', '葱花'],
    instructions: '1. 牛腩焯水加调料炖至软烂切片；2. 面条煮熟捞入碗；3. 浇牛肉汤放牛肉片青菜撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '馄饨',
    category: 'staple_onepot',
    tags: [TAGS.ELDERLY_FRIENDLY],
    ingredients: ['馄饨皮', '猪肉馅', '虾皮', '葱花', '紫菜', '香油', '盐'],
    instructions: '1. 肉馅加葱花虾皮盐香油调匀包成馄饨；2. 水开下馄饨煮至浮起；3. 加紫菜葱花香油调味即可。',
    rating: null,
    history_dates: [],
  },
  {
    name: '扬州炒饭',
    category: 'staple_onepot',
    tags: [],
    ingredients: ['米饭', '虾仁', '火腿', '青豆', '鸡蛋', '葱花', '盐', '生抽'],
    instructions: '1. 虾仁火腿切丁；2. 热油炒蛋加米饭大火炒散；3. 加虾仁火腿青豆翻炒调生抽盐撒葱花。',
    rating: null,
    history_dates: [],
  },
  {
    name: '担担面',
    category: 'staple_onepot',
    tags: [TAGS.SPICY],
    ingredients: ['面条', '猪肉末', '芽菜', '花生碎', '辣椒油', '芝麻酱', '生抽', '醋', '葱花'],
    instructions: '1. 碗底加芝麻酱辣椒油生抽醋调汁；2. 面条煮熟捞入碗中；3. 炒香肉末铺上加芽菜花生碎葱花拌食。',
    rating: null,
    history_dates: [],
  },
];
